### ISSUE TITLE
v7 - cannot find modules

### ISSUE THREAD

**Issue by lech206** [dolanmiu/docx#1198]
After upgrade from 6.0.3 to 7.0.0 I get many errors. Project Angular 12. What can be wrong? Thx

```
Error: node_modules/docx/build/export/packer/packer.d.ts:2:22 - error TS2307: Cannot find module 'file' or its corresponding type declarations.

2 import { File } from "file";
                       ~~~~~~


Error: node_modules/docx/build/file/app-properties/app-properties.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/border/border.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/content-types/content-types.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~




Error: node_modules/docx/build/file/paragraph/run/field.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/image-run.d.ts:2:42 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { IContext, IXmlableObject } from "file/xml-components";
                                           ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/properties.d.ts:1:46 - error TS2307: Cannot find module 'file/shading' or its corresponding type declarations.

1 import { IShadingAttributesProperties } from "file/shading";
                                               ~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/properties.d.ts:2:57 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { IgnoreIfEmptyXmlComponent, XmlComponent } from "file/xml-components";
                                                          ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/run-fonts.d.ts:1:30 - error0m TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/run.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/run.d.ts:2:38 - error TS2307: Cannot find module 'file/footnotes/footnote/run/reference-run' or its corresponding type declarations.

2 import { FootnoteReferenceRun } from "file/footnotes/footnote/run/reference-run";
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/run.d.ts:3:34 - error TS2307: Cannot find module 'file/table-of-contents/field-instruction' or its corresponding type declarations.

3 import { FieldInstruction } from "file/table-of-contents/field-instruction";
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/sequential-identifier.d.ts:1:21 - error TS2307: Cannot find module 'file/paragraph/run' or its corresponding type declarations.

1 import { Run } from "file/paragraph/run";
                      ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/simple-field.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/tab.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/paragraph/run/underline.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/relationships/relationship/relationship.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/relationships/relationships.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/settings/settings.d.ts:1:53 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlAttributeComponent, XmlComponent } from "file/xml-components";
                                                      ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/shading/shading.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/document-defaults.d.ts:1:50 - error TS2307: Cannot find module 'file/paragraph/properties' or its corresponding type declarations.

1 import { IParagraphStylePropertiesOptions } from "file/paragraph/properties";
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/document-defaults.d.ts:2:44 - error TS2307: Cannot find module 'file/paragraph/run/properties' or its corresponding type declarations.

2 import { IRunStylePropertiesOptions } from "file/paragraph/run/properties";
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/document-defaults.d.ts:3:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

3 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/paragraph-properties.d.ts:1:50 - error TS2307: Cannot find module 'file/paragraph/properties' or its corresponding type declarations.

1 import { IParagraphStylePropertiesOptions } from "file/paragraph/properties";
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/paragraph-properties.d.ts:2:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/run-properties.d.ts:1:44 - error TS2307: Cannot find module 'file/paragraph/run/properties' or its corresponding type declarations.

1 import { IRunStylePropertiesOptions } from "file/paragraph/run/properties";
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/defaults/run-properties.d.ts:2:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/style/character-style.d.ts:1:44 - error TS2307: Cannot find module 'file/paragraph/run/properties' or its corresponding type declarations.

1 import { IRunStylePropertiesOptions } from "file/paragraph/run/properties";
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/style/paragraph-style.d.ts:1:78 - error TS2307: Cannot find module 'file/paragraph' or its corresponding type declarations.

1 import { IParagraphStylePropertiesOptions, IRunStylePropertiesOptions } from "file/paragraph";
                                                                               ~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/style/style.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/styles.d.ts:1:39 - error TS2307: Cannot find module 'file/styles/factory' or its corresponding type declarations.

1 import { IDefaultStylesOptions } from "file/styles/factory";
                                        ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/styles/styles.d.ts:2:70 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { BaseXmlComponent, ImportedXmlComponent, XmlComponent } from "file/xml-components";
                                                                       ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table-of-contents/table-of-contents.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-cell/table-cell-components.d.ts:1:32 - error TS2307: Cannot find module 'file/border' or its corresponding type declarations.

1 import { IBorderOptions } from "file/border";
                                 ~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-cell/table-cell-components.d.ts:2:57 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { IgnoreIfEmptyXmlComponent, XmlComponent } from "file/xml-components";
                                                          ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-cell/table-cell-properties.d.ts:1:31 - error TS2307: Cannot find module 'file/vertical-align' or its corresponding type declarations.

1 import { VerticalAlign } from "file/vertical-align";
                                ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-cell/table-cell-properties.d.ts:2:43 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { IgnoreIfEmptyXmlComponent } from "file/xml-components";
                                            ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-cell/table-cell.d.ts:1:27 - error TS2307: Cannot find module 'file/paragraph' or its corresponding type declarations.

1 import { Paragraph } from "file/paragraph";
                            ~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-cell/table-cell.d.ts:2:56 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2[0m import { IContext, IXmlableObject, XmlComponent } from "file/xml-components";
                                                         ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-borders.d.ts:1:45 - error TS2307: Cannot find module 'file/border' or its corresponding type declarations.

1 import { BorderStyle, IBorderOptions } from "file/border";
                                              ~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-borders.d.ts:2:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

2 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-cell-margin.d.ts:1:43 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { IgnoreIfEmptyXmlComponent } from "file/xml-components";
                                            ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-float-properties.d.ts:1:53 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlAttributeComponent, XmlComponent } from "file/xml-components";
                                                      ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-layout.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-overlap.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-properties/table-properties.d.ts:1:43 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { IgnoreIfEmptyXmlComponent } from "file/xml-components";
                                            ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-row/table-row-height.d.ts:1:53 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlAttributeComponent, XmlComponent } from "file/xml-components";
                                                      ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-row/table-row-properties.d.ts:1:43 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { IgnoreIfEmptyXmlComponent } from "file/xml-components";
                                            ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-row/table-row.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table-width.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/table/table.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/track-revision/track-revision-components/deleted-text-run.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/track-revision/track-revision-components/inserted-text-run.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/track-revision/track-revision.d.ts:1:39 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlAttributeComponent } from "file/xml-components";
                                        ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/vertical-align/vertical-align.d.ts:1:53 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlAttributeComponent, XmlComponent } from "file/xml-components";
                                                      ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/xml-components/initializable-xml-component.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/file/xml-components/simple-elements.d.ts:1:30 - error TS2307: Cannot find module 'file/xml-components' or its corresponding type declarations.

1 import { XmlComponent } from "file/xml-components";
                               ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/import-dotx/import-dotx.d.ts:2:33 - error TS2307: Cannot find module 'file/footer-wrapper' or its corresponding type declarations.

2 import { IDocumentFooter } from "file/footer-wrapper";
                                  ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/import-dotx/import-dotx.d.ts:3:33 - error TS2307: Cannot find module 'file/header-wrapper' or its corresponding type declarations.

3 import { IDocumentHeader } from "file/header-wrapper";
                                  ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/docx/build/import-dotx/import-dotx.d.ts:4:23 - error TS2307: Cannot find module 'file/media' or its corresponding type declarations.

4 import { Media } from "file/media";
                        ~~~~~~~~~~~~
```

**Comment by dolanmiu** [comment]
Related to:

https://github.com/dolanmiu/docx/issues/1195

**Comment by dolanmiu** [comment]
Fixed in `7.1.0`
