### ISSUE TITLE
Cannot find module '../math-component'

### ISSUE THREAD

**Issue by elementalPRESS** [dolanmiu/docx#688]
Hi there,

after updating to v5.4 the following errors occur:

```
`ERROR in node_modules/docx/build/file/paragraph/math/math.d.ts:2:31 - error TS2307: Cannot find module './math-component' or its corresponding type declarations.

2 import { MathComponent } from "./math-component";
                                ~~~~~~~~~~~~~~~~~~
node_modules/docx/build/file/paragraph/math/fraction/math-fraction.d.ts:2:31 - error TS2307: Cannot find module '../math-component' or its corresponding type declarations.

2 import { MathComponent } from "../math-component";
                                ~~~~~~~~~~~~~~~~~~~
node_modules/docx/build/file/paragraph/math/fraction/math-denominator.d.ts:2:31 - error TS2307: Cannot find module '../math-component' or its corresponding type declarations.

...
```

The update process itself was flawless. But when compiling my code with `ng serve` in my Angular 10 environment the errors occur.

Thx for fixing!

**Comment by AmrasJidoka** [comment]
I can confirm I'm having the same issue with a clean install of 5.4.

**Comment by joaorizzont** [comment]
i'm having the same issue here to

**Comment by dolanmiu** [comment]
The issue:

https://github.com/s-panferov/awesome-typescript-loader/issues/432

Fixes with the following:


https://github.com/dolanmiu/docx/blob/master/src/file/media/data.ts#L19-L23

I'll make a PR soon

**Comment by dolanmiu** [comment]
Fixed in 5.4.1
